spring:
  mail:
    host: smtp.163.com
    username: hxq10082022@163.com
    password: UGezB4SdQGepz3dT
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin123
    virtual-host: /
  security:
    filter:
      order: -100
    jwt:
      key: abcdefijklm
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    verify:
      mail-limit: 60
    flow:
      period: 2
      limit: 50
      block: 30
  minio:
    endpoint: 'http://localhost:9000'
    username: 'minio'
    password: 'password'
  data:
    redis:
      port: 6385
      host: localhost
  weather:
    key: 3a2dd7429d5249bcbf7e36934dc267f1

